// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
insert into bookings (service_request_id, offer_id, garage_id, mechanic_id, scheduled_time)
values (
  $1, $2,
  nullif($3::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
  $4, $5
)
returning id, status, created_at
`

type CreateBookingParams struct {
	ServiceRequestID uuid.UUID
	OfferID          uuid.UUID
	GarageID         uuid.UUID
	MechanicID       *uuid.UUID
	ScheduledTime    *time.Time
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.ServiceRequestID, arg.OfferID, arg.GarageID, arg.MechanicID, arg.ScheduledTime)
	var i CreateBookingRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getBookingByRequest = `-- name: GetBookingByRequest :one
select id, service_request_id, offer_id, garage_id, mechanic_id, status,
       scheduled_time, started_at, completed_at, created_at
from bookings
where service_request_id = $1
`

func (q *Queries) GetBookingByRequest(ctx context.Context, requestID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByRequest, requestID)
	var i Booking
	err := row.Scan(&i.ID, &i.ServiceRequestID, &i.OfferID, &i.GarageID, &i.MechanicID, &i.Status, &i.ScheduledTime, &i.StartedAt, &i.CompletedAt, &i.CreatedAt)
	return i, err
}

const getBooking = `-- name: GetBooking :one
select id, service_request_id, offer_id, garage_id, mechanic_id, status,
       scheduled_time, started_at, completed_at, created_at
from bookings
where id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(&i.ID, &i.ServiceRequestID, &i.OfferID, &i.GarageID, &i.MechanicID, &i.Status, &i.ScheduledTime, &i.StartedAt, &i.CompletedAt, &i.CreatedAt)
	return i, err
}

const setBookingStatus = `-- name: SetBookingStatus :exec
update bookings
set status = $2,
    started_at = case when $2 = 'in_progress' then now() else started_at end,
    completed_at = case when $2 = 'completed' then now() else completed_at end,
    updated_at = now()
where id = $1
`

func (q *Queries) SetBookingStatus(ctx context.Context, id uuid.UUID, status string) error {
	_, err := q.db.Exec(ctx, setBookingStatus, id, status)
	return err
}
