// Code generated by sqlc. DO NOT EDIT BY HAND.
//
// This file (and the other *.sql.go files in this package) is normally
// produced by running `sqlc generate` against sqlc.yaml + the .sql files
// in internal/db/queries. It's hand-written here so the project compiles
// out of the box; once you install the sqlc CLI, running `sqlc generate`
// will overwrite this package with the real, exact output — do that
// before trusting this as the source of truth.
package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is satisfied by both *pgxpool.Pool and pgx.Tx, so the same
// generated Queries struct works whether you pass it a pool (normal
// request path) or a transaction (multi-step writes, e.g. accepting an
// offer + creating a booking atomically).
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

// WithTx returns a copy of Queries bound to the given transaction, for
// call sites that need several statements to commit or roll back together.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
