// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
insert into device_tokens (user_id, token, platform)
values ($1, $2, $3)
on conflict (token) do update
  set user_id = excluded.user_id, platform = excluded.platform, updated_at = now()
`

func (q *Queries) UpsertDeviceToken(ctx context.Context, userID uuid.UUID, token, platform string) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, userID, token, platform)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
delete from device_tokens where token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, token)
	return err
}

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
select token from device_tokens where user_id = $1
`

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tokens []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			return nil, err
		}
		tokens = append(tokens, t)
	}
	return tokens, rows.Err()
}
