// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listNearbyGarages = `-- name: ListNearbyGarages :many
select
  id, owner_id, name, address, is_verified,
  ST_Y(location::geometry) as latitude,
  ST_X(location::geometry) as longitude,
  ST_Distance(
    location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
  ) as distance_meters
from garages
where is_active = true
  and verification_status = 'approved'
  and ST_DWithin(
    location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    $3::float8
  )
order by distance_meters asc
limit $4::int
`

type ListNearbyGaragesParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	MaxResults   int32
}

func (q *Queries) ListNearbyGarages(ctx context.Context, arg ListNearbyGaragesParams) ([]ListNearbyGaragesRow, error) {
	rows, err := q.db.Query(ctx, listNearbyGarages, arg.Lng, arg.Lat, arg.RadiusMeters, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListNearbyGaragesRow
	for rows.Next() {
		var i ListNearbyGaragesRow
		if err := rows.Scan(&i.ID, &i.OwnerID, &i.Name, &i.Address, &i.IsVerified, &i.Latitude, &i.Longitude, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listNearbyGaragesOfferingCategory = `-- name: ListNearbyGaragesOfferingCategory :many
select
  g.id, g.owner_id, g.name, g.address, g.is_verified,
  ST_Y(g.location::geometry) as latitude,
  ST_X(g.location::geometry) as longitude,
  ST_Distance(
    g.location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
  ) as distance_meters
from garages g
join garage_service_categories gsc on gsc.garage_id = g.id
where g.is_active = true
  and g.verification_status = 'approved'
  and gsc.category_id = $3
  and ST_DWithin(
    g.location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    $4::float8
  )
order by distance_meters asc
limit $5::int
`

type ListNearbyGaragesOfferingCategoryParams struct {
	Lng          float64
	Lat          float64
	CategoryID   uuid.UUID
	RadiusMeters float64
	MaxResults   int32
}

func (q *Queries) ListNearbyGaragesOfferingCategory(ctx context.Context, arg ListNearbyGaragesOfferingCategoryParams) ([]ListNearbyGaragesOfferingCategoryRow, error) {
	rows, err := q.db.Query(ctx, listNearbyGaragesOfferingCategory, arg.Lng, arg.Lat, arg.CategoryID, arg.RadiusMeters, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListNearbyGaragesOfferingCategoryRow
	for rows.Next() {
		var i ListNearbyGaragesOfferingCategoryRow
		if err := rows.Scan(&i.ID, &i.OwnerID, &i.Name, &i.Address, &i.IsVerified, &i.Latitude, &i.Longitude, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getGarage = `-- name: GetGarage :one
select
  id, owner_id, name, description, address, phone, is_verified, is_active,
  verification_status, license_number,
  ST_Y(location::geometry) as latitude,
  ST_X(location::geometry) as longitude,
  created_at
from garages
where id = $1
`

func (q *Queries) GetGarage(ctx context.Context, id uuid.UUID) (GetGarageRow, error) {
	row := q.db.QueryRow(ctx, getGarage, id)
	var i GetGarageRow
	err := row.Scan(&i.ID, &i.OwnerID, &i.Name, &i.Description, &i.Address, &i.Phone, &i.IsVerified, &i.IsActive, &i.VerificationStatus, &i.LicenseNumber, &i.Latitude, &i.Longitude, &i.CreatedAt)
	return i, err
}

const createGarage = `-- name: CreateGarage :one
insert into garages (owner_id, name, description, address, phone, license_number, location)
values ($1, $2, $3, $4, $5, $6, ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography)
returning id, created_at
`

type CreateGarageParams struct {
	OwnerID       uuid.UUID
	Name          string
	Description   *string
	Address       *string
	Phone         *string
	LicenseNumber *string
	Lng           float64
	Lat           float64
}

func (q *Queries) CreateGarage(ctx context.Context, arg CreateGarageParams) (CreateGarageRow, error) {
	row := q.db.QueryRow(ctx, createGarage, arg.OwnerID, arg.Name, arg.Description, arg.Address, arg.Phone, arg.LicenseNumber, arg.Lng, arg.Lat)
	var i CreateGarageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listPendingGarages = `-- name: ListPendingGarages :many
select id, owner_id, name, license_number, address, submitted_at
from garages
where verification_status = 'pending'
order by submitted_at asc
`

func (q *Queries) ListPendingGarages(ctx context.Context) ([]ListPendingGaragesRow, error) {
	rows, err := q.db.Query(ctx, listPendingGarages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListPendingGaragesRow
	for rows.Next() {
		var i ListPendingGaragesRow
		if err := rows.Scan(&i.ID, &i.OwnerID, &i.Name, &i.LicenseNumber, &i.Address, &i.SubmittedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const setGarageVerificationStatus = `-- name: SetGarageVerificationStatus :exec
update garages
set verification_status = $2, reviewed_at = now(), reviewed_by = $3
where id = $1
`

func (q *Queries) SetGarageVerificationStatus(ctx context.Context, id uuid.UUID, status string, reviewedBy uuid.UUID) error {
	_, err := q.db.Exec(ctx, setGarageVerificationStatus, id, status, reviewedBy)
	return err
}

const addGarageServiceCategory = `-- name: AddGarageServiceCategory :exec
insert into garage_service_categories (garage_id, category_id)
values ($1, $2)
on conflict do nothing
`

func (q *Queries) AddGarageServiceCategory(ctx context.Context, garageID, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, addGarageServiceCategory, garageID, categoryID)
	return err
}


const deactivateGarage = `-- name: DeactivateGarage :exec
update garages set is_active = false, updated_at = now() where id = $1
`

func (q *Queries) DeactivateGarage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateGarage, id)
	return err
}

const deleteMechanicByID = `-- name: DeleteMechanicByID :exec
delete from mechanics where id = $1
`

func (q *Queries) DeleteMechanicByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMechanicByID, id)
	return err
}
