// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const updateMechanicLocation = `-- name: UpdateMechanicLocation :exec
update mechanics
set current_location = ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography,
    location_updated_at = now()
where id = $1
`

func (q *Queries) UpdateMechanicLocation(ctx context.Context, id uuid.UUID, lng, lat float64) error {
	_, err := q.db.Exec(ctx, updateMechanicLocation, id, lng, lat)
	return err
}

const insertMechanicLocationHistory = `-- name: InsertMechanicLocationHistory :exec
insert into mechanic_location_history (mechanic_id, booking_id, location)
values ($1, $2, ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326)::geography)
`

func (q *Queries) InsertMechanicLocationHistory(ctx context.Context, mechanicID uuid.UUID, bookingID uuid.UUID, lng, lat float64) error {
	_, err := q.db.Exec(ctx, insertMechanicLocationHistory, mechanicID, bookingID, lng, lat)
	return err
}

const getMechanicByProfileID = `-- name: GetMechanicByProfileID :one
select id, profile_id, garage_id, specialty, is_available
from mechanics
where profile_id = $1
`

func (q *Queries) GetMechanicByProfileID(ctx context.Context, profileID uuid.UUID) (GetMechanicByProfileIDRow, error) {
	row := q.db.QueryRow(ctx, getMechanicByProfileID, profileID)
	var i GetMechanicByProfileIDRow
	err := row.Scan(&i.ID, &i.ProfileID, &i.GarageID, &i.Specialty, &i.IsAvailable)
	return i, err
}
