// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Garage struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description *string
	Address     *string
	Phone       *string
	IsVerified  bool
	IsActive    bool
	CreatedAt   time.Time
}

type ListNearbyGaragesRow struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Name           string
	Address        *string
	IsVerified     bool
	Latitude       float64
	Longitude      float64
	DistanceMeters float64
}

type GetGarageRow struct {
	ID                 uuid.UUID
	OwnerID            uuid.UUID
	Name               string
	Description        *string
	Address            *string
	Phone              *string
	IsVerified         bool
	IsActive           bool
	VerificationStatus string
	LicenseNumber      *string
	Latitude           float64
	Longitude          float64
	CreatedAt          time.Time
}

type CreateGarageRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type ServiceRequest struct {
	ID          uuid.UUID
	CarOwnerID  uuid.UUID
	VehicleID   uuid.UUID
	CategoryID  uuid.UUID
	Description *string
	Status      string
	RequestedAt time.Time
	ScheduledAt *time.Time
	CreatedAt   time.Time
}

type CreateServiceRequestRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type GetServiceRequestRow struct {
	ID          uuid.UUID
	CarOwnerID  uuid.UUID
	VehicleID   uuid.UUID
	CategoryID  uuid.UUID
	Description *string
	Status      string
	PhotoURLs   []byte // raw jsonb; unmarshal in the repository layer
	Latitude    float64
	Longitude   float64
	RequestedAt time.Time
	ScheduledAt *time.Time
	CreatedAt   time.Time
}

type ListServiceRequestsByOwnerRow struct {
	ID          uuid.UUID
	VehicleID   uuid.UUID
	CategoryID  uuid.UUID
	Description *string
	Status      string
	RequestedAt time.Time
	ScheduledAt *time.Time
}

type ListOpenServiceRequestsNearRow struct {
	ID             uuid.UUID
	Description    *string
	Status         string
	RequestedAt    time.Time
	CategoryID     uuid.UUID
	Latitude       float64
	Longitude      float64
	DistanceMeters float64
	OwnerID        uuid.UUID
	OwnerName      *string
	OwnerPhone     *string
	OwnerAvatarURL *string
	VehicleID      uuid.UUID
	VehicleMake    *string
	VehicleModel   *string
	VehicleYear    *int32
	VehiclePlate   *string
	CategoryName   *string
}

type ListNearbyAvailableMechanicsRow struct {
	MechanicID     uuid.UUID
	ProfileID      uuid.UUID
	GarageID       *uuid.UUID
	Latitude       float64
	Longitude      float64
	DistanceMeters float64
}

// --- Garage verification / category matching -------------------------

type ListNearbyGaragesOfferingCategoryRow struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Name           string
	Address        *string
	IsVerified     bool
	Latitude       float64
	Longitude      float64
	DistanceMeters float64
}

type ListPendingGaragesRow struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Name          string
	LicenseNumber *string
	Address       *string
	SubmittedAt   time.Time
}

// --- Offers ------------------------------------------------------------

type Offer struct {
	ID               uuid.UUID
	ServiceRequestID uuid.UUID
	GarageID         uuid.UUID
	MechanicID       *uuid.UUID
	Price            string // numeric comes back as string via pgx by default
	Currency         string
	EtaMinutes       *int32
	Notes            *string
	Status           string
	CreatedAt        time.Time
}

type CreateOfferRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

// --- Bookings ------------------------------------------------------------

type Booking struct {
	ID               uuid.UUID
	ServiceRequestID uuid.UUID
	OfferID          uuid.UUID
	GarageID         uuid.UUID
	MechanicID       *uuid.UUID
	Status           string
	ScheduledTime    *time.Time
	StartedAt        *time.Time
	CompletedAt      *time.Time
	CreatedAt        time.Time
}

type CreateBookingRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

// --- Profiles ------------------------------------------------------------

type GetProfileRoleRow struct {
	ID       uuid.UUID
	Role     string
	FullName string
	IsActive bool
}

// --- Mechanics ------------------------------------------------------------

type GetMechanicByProfileIDRow struct {
	ID          uuid.UUID
	ProfileID   uuid.UUID
	GarageID    uuid.UUID
	Specialty   *string
	IsAvailable bool
}

// --- Payments ------------------------------------------------------------

type CreatePaymentRow struct {
	ID            uuid.UUID
	Status        string
	ProviderTxRef *string
	CreatedAt     time.Time
}

type Payment struct {
	ID                    uuid.UUID
	BookingID             uuid.UUID
	Amount                string
	Currency              string
	Method                string
	Status                string
	Provider              string
	ProviderTxRef         *string
	ProviderTransactionID *string
	PaidAt                *time.Time
	CreatedAt             time.Time
}

// --- Reviews ------------------------------------------------------------

type CreateReviewRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type ReviewRow struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	ReviewerID uuid.UUID
	Rating     int32
	Comment    *string
	CreatedAt  time.Time
}
