// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createOffer = `-- name: CreateOffer :one
insert into offers (service_request_id, garage_id, mechanic_id, price, currency, eta_minutes, notes)
values (
  $1,
  nullif($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
  $3, $4, $5, $6, $7
)
returning id, status, created_at
`

type CreateOfferParams struct {
	ServiceRequestID uuid.UUID
	GarageID         uuid.UUID
	MechanicID       *uuid.UUID
	Price            string
	Currency         string
	EtaMinutes       *int32
	Notes            *string
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (CreateOfferRow, error) {
	row := q.db.QueryRow(ctx, createOffer, arg.ServiceRequestID, arg.GarageID, arg.MechanicID, arg.Price, arg.Currency, arg.EtaMinutes, arg.Notes)
	var i CreateOfferRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getOffer = `-- name: GetOffer :one
select id, service_request_id, garage_id, mechanic_id, price, currency, eta_minutes, notes, status, created_at
from offers
where id = $1
`

func (q *Queries) GetOffer(ctx context.Context, id uuid.UUID) (Offer, error) {
	row := q.db.QueryRow(ctx, getOffer, id)
	var i Offer
	err := row.Scan(&i.ID, &i.ServiceRequestID, &i.GarageID, &i.MechanicID, &i.Price, &i.Currency, &i.EtaMinutes, &i.Notes, &i.Status, &i.CreatedAt)
	return i, err
}

const listOffersForRequest = `-- name: ListOffersForRequest :many
select id, service_request_id, garage_id, mechanic_id, price, currency, eta_minutes, notes, status, created_at
from offers
where service_request_id = $1
order by created_at asc
`

func (q *Queries) ListOffersForRequest(ctx context.Context, requestID uuid.UUID) ([]Offer, error) {
	rows, err := q.db.Query(ctx, listOffersForRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(&i.ID, &i.ServiceRequestID, &i.GarageID, &i.MechanicID, &i.Price, &i.Currency, &i.EtaMinutes, &i.Notes, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const setOfferStatus = `-- name: SetOfferStatus :exec
update offers set status = $2, responded_at = now() where id = $1
`

func (q *Queries) SetOfferStatus(ctx context.Context, id uuid.UUID, status string) error {
	_, err := q.db.Exec(ctx, setOfferStatus, id, status)
	return err
}

const rejectOtherOffers = `-- name: RejectOtherOffers :exec
update offers
set status = 'rejected', responded_at = now()
where service_request_id = $1 and id <> $2 and status = 'pending'
`

func (q *Queries) RejectOtherOffers(ctx context.Context, requestID, winningOfferID uuid.UUID) error {
	_, err := q.db.Exec(ctx, rejectOtherOffers, requestID, winningOfferID)
	return err
}
