// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
insert into payments (booking_id, amount, currency, method, status, provider, provider_tx_ref)
values ($1, $2, $3, 'mobile_money', 'pending', $4, $5)
returning id, status, provider_tx_ref, created_at
`

type CreatePaymentParams struct {
	BookingID     uuid.UUID
	Amount        string
	Currency      string
	Provider      string
	ProviderTxRef string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.BookingID, arg.Amount, arg.Currency, arg.Provider, arg.ProviderTxRef)
	var i CreatePaymentRow
	err := row.Scan(&i.ID, &i.Status, &i.ProviderTxRef, &i.CreatedAt)
	return i, err
}

const getPaymentByTxRef = `-- name: GetPaymentByTxRef :one
select id, booking_id, amount, currency, method, status, provider,
       provider_tx_ref, provider_transaction_id, paid_at, created_at
from payments
where provider_tx_ref = $1
`

func (q *Queries) GetPaymentByTxRef(ctx context.Context, txRef string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTxRef, txRef)
	var i Payment
	err := row.Scan(&i.ID, &i.BookingID, &i.Amount, &i.Currency, &i.Method, &i.Status, &i.Provider, &i.ProviderTxRef, &i.ProviderTransactionID, &i.PaidAt, &i.CreatedAt)
	return i, err
}

const getPaymentByBooking = `-- name: GetPaymentByBooking :one
select id, booking_id, amount, currency, method, status, provider,
       provider_tx_ref, provider_transaction_id, paid_at, created_at
from payments
where booking_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBooking, bookingID)
	var i Payment
	err := row.Scan(&i.ID, &i.BookingID, &i.Amount, &i.Currency, &i.Method, &i.Status, &i.Provider, &i.ProviderTxRef, &i.ProviderTransactionID, &i.PaidAt, &i.CreatedAt)
	return i, err
}

const updatePaymentProviderTxRef = `-- name: UpdatePaymentProviderTxRef :exec
update payments
set provider_tx_ref = $2
where provider_tx_ref = $1
`

func (q *Queries) UpdatePaymentProviderTxRef(ctx context.Context, oldTxRef, newTxRef string) error {
	_, err := q.db.Exec(ctx, updatePaymentProviderTxRef, oldTxRef, newTxRef)
	return err
}

const markPaymentSettled = `-- name: MarkPaymentSettled :exec
update payments
set status = $2, provider_transaction_id = $3, raw_webhook_payload = $4,
    paid_at = case when $2 = 'paid' then now() else paid_at end
where provider_tx_ref = $1
`

func (q *Queries) MarkPaymentSettled(ctx context.Context, txRef, status string, providerTxnID *string, rawPayload []byte) error {
	_, err := q.db.Exec(ctx, markPaymentSettled, txRef, status, providerTxnID, rawPayload)
	return err
}
