// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getProfileRole = `-- name: GetProfileRole :one
select id, role, full_name, is_active
from profiles
where id = $1
`

func (q *Queries) GetProfileRole(ctx context.Context, id uuid.UUID) (GetProfileRoleRow, error) {
	row := q.db.QueryRow(ctx, getProfileRole, id)
	var i GetProfileRoleRow
	err := row.Scan(&i.ID, &i.Role, &i.FullName, &i.IsActive)
	return i, err
}
