// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
insert into reviews (booking_id, reviewer_id, garage_id, mechanic_id, rating, comment)
values ($1, $2, $3, $4, $5, $6)
returning id, created_at
`

type CreateReviewParams struct {
	BookingID  uuid.UUID
	ReviewerID uuid.UUID
	GarageID   *uuid.UUID
	MechanicID *uuid.UUID
	Rating     int32
	Comment    *string
}

type CreateReviewRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type ReviewRow struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	ReviewerID uuid.UUID
	Rating     int32
	Comment    *string
	CreatedAt  time.Time
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error) {
	row := q.db.QueryRow(ctx, createReview, arg.BookingID, arg.ReviewerID, arg.GarageID, arg.MechanicID, arg.Rating, arg.Comment)
	var i CreateReviewRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const reviewExists = `-- name: ReviewExists :one
select exists(
  select 1 from reviews
  where booking_id = $1 and reviewer_id = $2
    and coalesce(garage_id, '00000000-0000-0000-0000-000000000000') = coalesce($3, '00000000-0000-0000-0000-000000000000')
    and coalesce(mechanic_id, '00000000-0000-0000-0000-000000000000') = coalesce($4, '00000000-0000-0000-0000-000000000000')
) as exists
`

func (q *Queries) ReviewExists(ctx context.Context, bookingID, reviewerID uuid.UUID, garageID, mechanicID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, reviewExists, bookingID, reviewerID, garageID, mechanicID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listReviewsForGarage = `-- name: ListReviewsForGarage :many
select id, booking_id, reviewer_id, rating, comment, created_at
from reviews where garage_id = $1
order by created_at desc
limit $2::int
`

func (q *Queries) ListReviewsForGarage(ctx context.Context, garageID uuid.UUID, limit int32) ([]ReviewRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForGarage, garageID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewRow
	for rows.Next() {
		var i ReviewRow
		if err := rows.Scan(&i.ID, &i.BookingID, &i.ReviewerID, &i.Rating, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listReviewsForMechanic = `-- name: ListReviewsForMechanic :many
select id, booking_id, reviewer_id, rating, comment, created_at
from reviews where mechanic_id = $1
order by created_at desc
limit $2::int
`

func (q *Queries) ListReviewsForMechanic(ctx context.Context, mechanicID uuid.UUID, limit int32) ([]ReviewRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForMechanic, mechanicID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewRow
	for rows.Next() {
		var i ReviewRow
		if err := rows.Scan(&i.ID, &i.BookingID, &i.ReviewerID, &i.Rating, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
