// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createServiceRequest = `-- name: CreateServiceRequest :one
insert into service_requests (car_owner_id, vehicle_id, category_id, description, pickup_location, photo_urls)
values ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography, $7::jsonb)
returning id, status, created_at
`

type CreateServiceRequestParams struct {
	CarOwnerID  uuid.UUID
	VehicleID   uuid.UUID
	CategoryID  uuid.UUID
	Description *string
	Lng         float64
	Lat         float64
	PhotoURLs   []byte // marshaled JSON array, e.g. []byte(`["https://..."]`)
}

func (q *Queries) CreateServiceRequest(ctx context.Context, arg CreateServiceRequestParams) (CreateServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, createServiceRequest, arg.CarOwnerID, arg.VehicleID, arg.CategoryID, arg.Description, arg.Lng, arg.Lat, arg.PhotoURLs)
	var i CreateServiceRequestRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getServiceRequest = `-- name: GetServiceRequest :one
select
  id, car_owner_id, vehicle_id, category_id, description, status, photo_urls,
  ST_Y(pickup_location::geometry) as latitude,
  ST_X(pickup_location::geometry) as longitude,
  requested_at, scheduled_at, created_at
from service_requests
where id = $1
`

func (q *Queries) GetServiceRequest(ctx context.Context, id uuid.UUID) (GetServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequest, id)
	var i GetServiceRequestRow
	err := row.Scan(&i.ID, &i.CarOwnerID, &i.VehicleID, &i.CategoryID, &i.Description, &i.Status, &i.PhotoURLs, &i.Latitude, &i.Longitude, &i.RequestedAt, &i.ScheduledAt, &i.CreatedAt)
	return i, err
}

const listServiceRequestsByOwner = `-- name: ListServiceRequestsByOwner :many
select id, vehicle_id, category_id, description, status, requested_at, scheduled_at
from service_requests
where car_owner_id = $1
order by requested_at desc
limit $2::int
`

type ListServiceRequestsByOwnerParams struct {
	CarOwnerID uuid.UUID
	MaxResults int32
}

func (q *Queries) ListServiceRequestsByOwner(ctx context.Context, arg ListServiceRequestsByOwnerParams) ([]ListServiceRequestsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestsByOwner, arg.CarOwnerID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListServiceRequestsByOwnerRow
	for rows.Next() {
		var i ListServiceRequestsByOwnerRow
		if err := rows.Scan(&i.ID, &i.VehicleID, &i.CategoryID, &i.Description, &i.Status, &i.RequestedAt, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listOpenServiceRequestsNear = `-- name: ListOpenServiceRequestsNear :many
select
  sr.id, sr.description, sr.status, sr.requested_at,
  ST_Y(sr.pickup_location::geometry) as latitude,
  ST_X(sr.pickup_location::geometry) as longitude,
  ST_Distance(
    sr.pickup_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
  ) as distance_meters
from service_requests sr
where sr.status = 'pending'
  and ST_DWithin(
    sr.pickup_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    $3::float8
  )
order by distance_meters asc
limit $4::int
`

type ListOpenServiceRequestsNearParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	MaxResults   int32
}

func (q *Queries) ListOpenServiceRequestsNear(ctx context.Context, arg ListOpenServiceRequestsNearParams) ([]ListOpenServiceRequestsNearRow, error) {
	rows, err := q.db.Query(ctx, listOpenServiceRequestsNear, arg.Lng, arg.Lat, arg.RadiusMeters, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListOpenServiceRequestsNearRow
	for rows.Next() {
		var i ListOpenServiceRequestsNearRow
		if err := rows.Scan(&i.ID, &i.Description, &i.Status, &i.RequestedAt, &i.Latitude, &i.Longitude, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateServiceRequestStatus = `-- name: UpdateServiceRequestStatus :exec
update service_requests
set status = $2, updated_at = now()
where id = $1
`

func (q *Queries) UpdateServiceRequestStatus(ctx context.Context, id uuid.UUID, status string) error {
	_, err := q.db.Exec(ctx, updateServiceRequestStatus, id, status)
	return err
}
