// Code generated by sqlc. DO NOT EDIT BY HAND. See db.go for context.
package sqlcgen

import (
	"context"
	"errors"

	"github.com/google/uuid"
)

var ErrNoRows = errors.New("no rows")

const createServiceRequest = `-- name: CreateServiceRequest :one
insert into service_requests (car_owner_id, vehicle_id, category_id, description, pickup_location, photo_urls, request_kind)
values ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography, $7::jsonb, coalesce(nullif($8::text, ''), 'mechanic_request'))
returning id, status, created_at
`

type CreateServiceRequestParams struct {
	CarOwnerID  uuid.UUID
	VehicleID   uuid.UUID
	CategoryID  uuid.UUID
	Description *string
	Lng         float64
	Lat         float64
	PhotoURLs   []byte // marshaled JSON array, e.g. []byte(`["https://..."]`)
	RequestKind string
}

func (q *Queries) CreateServiceRequest(ctx context.Context, arg CreateServiceRequestParams) (CreateServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, createServiceRequest, arg.CarOwnerID, arg.VehicleID, arg.CategoryID, arg.Description, arg.Lng, arg.Lat, arg.PhotoURLs, arg.RequestKind)
	var i CreateServiceRequestRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getServiceRequest = `-- name: GetServiceRequest :one
select
  id, car_owner_id, vehicle_id, category_id, description, status, photo_urls,
  ST_Y(pickup_location::geometry) as latitude,
  ST_X(pickup_location::geometry) as longitude,
  requested_at, scheduled_at, created_at
from service_requests
where id = $1
`

func (q *Queries) GetServiceRequest(ctx context.Context, id uuid.UUID) (GetServiceRequestRow, error) {
	row := q.db.QueryRow(ctx, getServiceRequest, id)
	var i GetServiceRequestRow
	err := row.Scan(&i.ID, &i.CarOwnerID, &i.VehicleID, &i.CategoryID, &i.Description, &i.Status, &i.PhotoURLs, &i.Latitude, &i.Longitude, &i.RequestedAt, &i.ScheduledAt, &i.CreatedAt)
	return i, err
}

const listServiceRequestsByOwner = `-- name: ListServiceRequestsByOwner :many
select id, vehicle_id, category_id, description, status, requested_at, scheduled_at
from service_requests
where car_owner_id = $1
order by requested_at desc
limit $2::int
`

type ListServiceRequestsByOwnerParams struct {
	CarOwnerID uuid.UUID
	MaxResults int32
}

func (q *Queries) ListServiceRequestsByOwner(ctx context.Context, arg ListServiceRequestsByOwnerParams) ([]ListServiceRequestsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listServiceRequestsByOwner, arg.CarOwnerID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListServiceRequestsByOwnerRow
	for rows.Next() {
		var i ListServiceRequestsByOwnerRow
		if err := rows.Scan(&i.ID, &i.VehicleID, &i.CategoryID, &i.Description, &i.Status, &i.RequestedAt, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listOpenServiceRequestsNear = `-- name: ListOpenServiceRequestsNear :many
-- All pending requests, closest first. Radius is soft: we still return
-- everything pending so demos / wrong GPS still show the inbox.
select
  sr.id, sr.description, sr.status, sr.requested_at,
  coalesce(sr.request_kind, 'mechanic_request') as request_kind,
  coalesce(sr.category_id, '00000000-0000-0000-0000-000000000000'::uuid) as category_id,
  coalesce(ST_Y(sr.pickup_location::geometry), 0) as latitude,
  coalesce(ST_X(sr.pickup_location::geometry), 0) as longitude,
  coalesce(ST_Distance(
    sr.pickup_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
  ), 0) as distance_meters,
  p.id as owner_id,
  p.full_name as owner_name,
  p.phone as owner_phone,
  p.avatar_url as owner_avatar_url,
  coalesce(v.id, '00000000-0000-0000-0000-000000000000'::uuid) as vehicle_id,
  v.make as vehicle_make,
  v.model as vehicle_model,
  v.year as vehicle_year,
  v.plate_number as vehicle_plate,
  sc.name as category_name
from service_requests sr
join profiles p on p.id = sr.car_owner_id
left join vehicles v on v.id = sr.vehicle_id
left join service_categories sc on sc.id = sr.category_id
where sr.status in ('pending', 'quoted')
order by distance_meters asc nulls last, sr.requested_at desc
limit $4::int
`

type ListOpenServiceRequestsNearParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	MaxResults   int32
}

func (q *Queries) ListOpenServiceRequestsNear(ctx context.Context, arg ListOpenServiceRequestsNearParams) ([]ListOpenServiceRequestsNearRow, error) {
	rows, err := q.db.Query(ctx, listOpenServiceRequestsNear, arg.Lng, arg.Lat, arg.RadiusMeters, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListOpenServiceRequestsNearRow
	for rows.Next() {
		var i ListOpenServiceRequestsNearRow
		if err := rows.Scan(
			&i.ID, &i.Description, &i.Status, &i.RequestedAt, &i.RequestKind, &i.CategoryID,
			&i.Latitude, &i.Longitude, &i.DistanceMeters,
			&i.OwnerID, &i.OwnerName, &i.OwnerPhone, &i.OwnerAvatarURL,
			&i.VehicleID, &i.VehicleMake, &i.VehicleModel, &i.VehicleYear, &i.VehiclePlate,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateServiceRequestStatus = `-- name: UpdateServiceRequestStatus :exec
update service_requests
set status = $2, updated_at = now()
where id = $1
`

func (q *Queries) UpdateServiceRequestStatus(ctx context.Context, id uuid.UUID, status string) error {
	_, err := q.db.Exec(ctx, updateServiceRequestStatus, id, status)
	return err
}

const cancelServiceRequest = `-- name: CancelServiceRequest :exec
update service_requests
set status = 'cancelled', updated_at = now()
where id = $1
  and car_owner_id = $2
  and status in ('pending', 'quoted')
`

type CancelServiceRequestParams struct {
	ID         uuid.UUID
	CarOwnerID uuid.UUID
}

func (q *Queries) CancelServiceRequest(ctx context.Context, arg CancelServiceRequestParams) error {
	tag, err := q.db.Exec(ctx, cancelServiceRequest, arg.ID, arg.CarOwnerID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNoRows
	}
	return nil
}

const listNearbyAvailableMechanics = `-- name: ListNearbyAvailableMechanics :many
select
  m.id as mechanic_id,
  m.profile_id,
  m.garage_id,
  ST_Y(m.current_location::geometry) as latitude,
  ST_X(m.current_location::geometry) as longitude,
  ST_Distance(
    m.current_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
  ) as distance_meters
from mechanics m
where m.current_location is not null
  and ST_DWithin(
    m.current_location,
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    $3::float8
  )
order by distance_meters asc
limit $4::int
`

type ListNearbyAvailableMechanicsParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	MaxResults   int32
}

func (q *Queries) ListNearbyAvailableMechanics(ctx context.Context, arg ListNearbyAvailableMechanicsParams) ([]ListNearbyAvailableMechanicsRow, error) {
	rows, err := q.db.Query(ctx, listNearbyAvailableMechanics, arg.Lng, arg.Lat, arg.RadiusMeters, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyAvailableMechanicsRow
	for rows.Next() {
		var i ListNearbyAvailableMechanicsRow
		if err := rows.Scan(&i.MechanicID, &i.ProfileID, &i.GarageID, &i.Latitude, &i.Longitude, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
